# Generated by Django 4.1.4 on 2023-03-03 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Schema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=63, null=True)),
                (
                    "column_separator",
                    models.TextField(
                        choices=[
                            (",", "Comma(,)"),
                            (";", "Semilicon(;)"),
                            (" ", "Space( )"),
                            ("|", "Pipe(|)"),
                        ],
                        default=",",
                        max_length=1,
                    ),
                ),
                (
                    "string_character",
                    models.TextField(
                        choices=[('"', 'Double-quote(")'), ("'", "Single-quote(')")],
                        default='""',
                        max_length=1,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schemas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated"],
            },
        ),
        migrations.CreateModel(
            name="DataSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Processing.."), (1, "Ready!")], default=0
                    ),
                ),
                ("rows", models.PositiveIntegerField(null=True)),
                ("download_link", models.URLField()),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schemadatasets",
                        to="test_task.schema",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Column",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("column_name", models.CharField(max_length=20)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("Full_name", "Full name"),
                            ("Job", "Job"),
                            ("Email", "Email"),
                            ("Domain_name", "Domain name"),
                            ("Phone_number", "Phone number"),
                            ("Company_name", "Company name"),
                            ("Text", "Text"),
                            ("Integer", "Integer"),
                            ("Address", "Address"),
                            ("Date", "Date"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schemacolumns",
                        to="test_task.schema",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
